import Image from "next/image";
import Link from "next/link";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Carousel } from "@/components/Carousel";

const offers = [{ title: "Graviato", text: "Premium wall finishes that stand out." }, { title: "Paint & decor", text: "Top brands, vibrant colours, lasting results." }, { title: "Delivery", text: "Fast, reliable delivery nationwide." }, { title: "Guidance", text: "Practical help from first idea to final coat." }];

export default function Home() {
  return <><Header /><main><section className="hero"><div className="hero-grid"><div className="hero-copy"><div className="founder-profile"><div className="founder-photo"><Image src="/profile.jpg" alt="Sherif Issahaku, CEO and Founder of Paint & Decor Hub" fill sizes="96px" /></div><p className="founder-name">Sherif Issahaku</p><p className="founder-role">CEO &amp; Founder</p></div><p className="eyebrow">Premium finishes · Nationwide delivery</p><h1>Bring colour<br />to <em>life.</em></h1><p>Paint, texture, and decor chosen to make your space feel considered. Beautiful finishes, trusted products, and a team that cares about the details.</p><div className="hero-actions"><Link className="btn-primary" href="/contact">Start your project <span>↗</span></Link><Link className="btn-secondary" href="/services">Explore services <span>↗</span></Link></div><div className="proof-bar"><div className="proof"><strong>01</strong><span>Quality first</span></div><div className="proof"><strong>02</strong><span>Made to last</span></div><div className="proof"><strong>03</strong><span>We deliver</span></div></div></div><div className="hero-media"><span className="hero-badge">Choose<br />quality<br />Graviato</span><div className="hero-image"><Image src="/best.jpg" alt="Modern home finished with Graviato textured paint" fill priority sizes="(max-width: 850px) 100vw, 55vw" /></div><div className="hero-tag"><small>The signature finish</small><strong>Graviato</strong></div></div></div></section><section className="split-section"><div className="split-inner"><div><p className="eyebrow">The difference is visible</p><h2 className="section-title">A finish that<br /><em>feels like you.</em></h2><p className="section-copy">Beautiful homes begin with products that perform. Our textured finishes pair lasting protection with a look you will love coming home to.</p><Link className="btn-secondary" href="/blog">Read the blog <span>↗</span></Link></div><Carousel /></div></section><section className="offer-section"><div className="offer-inner"><div className="offer-heading"><div><p className="eyebrow">What we offer</p><h2>Good spaces<br /><em>start here.</em></h2></div><Link className="btn-secondary" href="/services">All services <span>↗</span></Link></div><div className="offer-grid">{offers.map((offer, index) => <article className="offer-card" key={offer.title}><span className="offer-number">0{index + 1}</span><h3>{offer.title}</h3><p>{offer.text}</p></article>)}</div></div></section><section className="cta-band"><div className="cta-inner"><h2>Let’s talk colour.</h2><Link className="btn-primary btn-dark" href="/contact">Get in touch <span>↗</span></Link></div></section></main><Footer /></>;
}
